[package]
name = "bbshark"
version = "0.1.0"
authors = [ "dunlopWill" ]
edition = "2024"
rust-version = "1.88.0"
description = "Prints a very popular kid's song."
license = "MIT"

[dependencies]
clap = "2.33"

[dev-dependencies]
assert_cmd = "1"